name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
# inputs:
#   python-version:
#     description: 'Python version to use'
#     required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4  
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Create tmp directory
      run: mkdir -p ./tmp
      shell: bash
    - name: Create external requirements.txt
      run: echo "pytest==7.0.0" > ./tmp/ext-reqs.txt
      shell: bash
  
    - name: Set up python
      uses: aparnajyothi-y/setup-python@fix-overwriting
      # uses: actions/setup-python@v5
      with:
        # python-version : ${{ inputs.python-version }}
        python-version:  '3.13'
        cache: pip
        overwrite: true      
        cache-dependency-path: ./tmp/ext-reqs.txt
        
    - run: pip install -r ./tmp/ext-reqs.txt
      shell: bash