name: check latest

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Clear cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: |
            3.14-dev
            3.15-dev