name: check latest

on:
  # push:
  #   branches:
  #     - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest, windows-11-arm]
        # os: [windows-2025, windows-latest, windows-2019, windows-11-arm]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        # uses: actions/setup-python@v5
        uses: lmvysakh/setup-python@enhance-python-version-readability
        with:
          python-version-file: '.python-version' 
          # python-version: '>=3.9 <3.14'
          # freethreaded: true
          # check-latest: true
      - name: Verify Python Version
        run: |
          python --version




