name: Test Using the python-version-file input

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest, macos-13, macos-latest]
        # python-version: ['3.13.1t', '3.13.1', '3.12', '3.11', '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        # uses: lmvysakh/setup-python@enhance-python-version-readability
        # uses: priya-kinthali/setup-python@sample-361
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: sub-project/pyproject.toml

      - name: Install poetry
        # working-directory: sub-project
        run: poetry install
      # - run: poetry install --no-root


      - name: Verify Python Version
        run: |
            python --version




