name: Test 1079 with fix

on:
  push:
    branches:
      - test-973
  workflow_dispatch:
jobs:
          test:
            runs-on: windows-latest
            steps:
              - name: Checkout code
                uses: actions/checkout@v4

              - name: Set up Python 3.9
                uses: actions/setup-python@v5
                with:
                  python-version: 3.9
              - name: Get Python 3.9 path
                id: py39
                run: echo "PY39_PATH=$(which python)" >> $GITHUB_ENV

              - name: Set up Python 3.13
                uses: actions/setup-python@v5
                with:
                  python-version: 3.13
              - name: Get Python 3.13 path
                id: py313
                run: echo "PY313_PATH=$(which python)" >> $GITHUB_ENV

              - name: Use both Python versions
                run: |
                  echo "Python 3.9 path: $PY39_PATH"
                  echo "Python 3.13 path: $PY313_PATH"
                  $PY39_PATH --version
                  $PY313_PATH --version

     