name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        # os: [windows-latest, macos-latest, ubuntu-latest]
        os: [windows-latest]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: |
      #       3.9
      #       3.13
      - name: Manually install Python 3.13.1 on Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "Downloading Python 3.13.1 installer..."
          curl -o $env:USERPROFILE\\python-installer.exe https://www.python.org/ftp/python/3.13.1/python-3.13.1-amd64.exe
          
          echo "Installing Python 3.13.1..."
          & $env:USERPROFILE\\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1
          
          echo "Locating Python installation..."
          $pythonPath = (where python | Select-String -Pattern "C:\\.*python.exe").Matches.Value
          
          if (-not $pythonPath) {
            echo "Attempting to locate Python in default installation paths..."
            $defaultPaths = @(
              "C:\Program Files\Python3131\python.exe",
              "$env:LOCALAPPDATA\Programs\Python\Python3131\python.exe"
            )
            foreach ($path in $defaultPaths) {
              if (Test-Path $path) {
                $pythonPath = $path
                break
              }
            }
          }
          
          if (-not $pythonPath) {
            Write-Error "Python installation not found."
            exit 1
          }
          
          echo "Checking Python version directly from installation path..."
          & $pythonPath --version
          
          echo "Listing all files in the Python installation directory..."
          $pythonDir = Split-Path -Path $pythonPath
          Get-ChildItem -Path $pythonDir -Recurse -Force

      # - name: Check for Python 3.13 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.13.1 /s /b
      # - name: Check for Python 3.13 on macOS
      #   if: runner.os == 'macOS'
      #   shell: bash
      #   run: |
      #     echo "Checking Python files on macOS..."
      #     find /Users/runner/hostedtoolcache/Python/3.13.2

      # - name: Check for Python 3.13 on Linux
      #   if: runner.os == 'Linux'
      #   shell: bash
      #   run: |
      #     echo "Checking Python files on Linux..."
      #     find /opt/hostedtoolcache/Python/3.13.2
      # - name: Check for Python 3.13 on non-Windows
      #   if: runner.os != 'Windows'
      #   run: |
      #     command -v python3.13 || echo "python3.13 not found on ${{ matrix.os }}"
      

