name: Python Setup with astral-sh/setup-uv

on:
  push:
    branches:
      - test-973
  pull_request:

jobs:
  test-python-executables:
    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x64, x86]
        python-version: [3.11, 3.12, 3.10]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Verify Tcl directory contents
        run: |
          echo "Python version: $(python --version)"
          echo "Checking Tcl directory contents..."
          $PYTHON_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')")
          dir C:\hostedtoolcache\windows\Python\$PYTHON_VERSION\x64\tcl\tcl8.6
        shell: pwsh