name: Test Multiple Python Versions (3.13t -> 3.13)

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [macos-13, macos-14]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify python
        run: |
          python -VVV
          which python
      - name: Clear cache
        run: |
            rm -rf "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
            mkdir -p "${{ runner.tool_cache }}"

      - name: Verify python
        run: |
          python -VVV
          which python
      - name: Generate requirements file
        run: python -m pip freeze > requirements-test.txt
      - name: Set up python
        uses: gowridurgad/setup-python@pip-install
        # uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
          cache: pip
          pip-install: -r requirements-test.txt

      - name: Contents of generated file
        run: cat requirements-test.txt
      # - name: Install dependencies in another environment
      #   run: python -m pip install -r requirements-test.txt
      # - name: Verify Python Version
      #   run: |
      #     python -VVV
      #     which python
      # - name: Run script
      #   run: python hello.py
      # - name: Install dependencies
      #   run: pip install -r requirements-dev.txt