name: Test pythonLocation on All Runners and python-versions

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-location:
    name: "Test ${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        python-version: [ '3.10', '3.10.10', '3.13', '3.13.1', 'pypy-3.10', 'pypy3.10-v7.3.17', 'pypy3.10-v7.3.19', 'graalpy-24.2.2' ]
        exclude:
          - python-version: 'graalpy-24.2.2'
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print pythonLocation and Executable Info
        shell: bash
        run: |
          echo "OS: $RUNNER_OS"
          echo "value of pythonLocation: $pythonLocation"
          echo "Which python from PATH: $(which python || where python)"
          python --version
          echo "Python executable location (from sys.executable):"
          python -c "import sys; print(sys.executable)"
          if [ "$RUNNER_OS" = "Windows" ]; then
            where python.exe || echo "python.exe not found"
          else
            which python || echo "python not found"
          fi
          