name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.13
      - name: Check for Python 3.13 on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Checking Python DLLs..."
          dir C:\hostedtoolcache\windows\Python /s /b

      # - name: Check for Python 3.13 on non-Windows
      #   if: runner.os != 'Windows'
      #   run: |
      #     command -v python3.13 || echo "python3.13 not found on ${{ matrix.os }}"
      

