# .github/workflows/test-python-versions.yml
name: Test Python Minor Versions

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-multiple-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-22.04-arm]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6

      - name: Clear cache
        run: |
            mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
            mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Python
        # uses: actions/setup-python@v6
        uses: priya-kinthali/setup-python@test-1079-new
        with:
          python-version: |
            3.13
            3.14

      - name: Check available python executables
        shell: bash
        run: |
          echo "Checking python executables"
          which python
          which python3
          which python3.13 || echo "python3.13 not found"
          which python3.14 || echo "python3.14 not found"
          command -v python || echo "python not found"
          command -v python3.13 || echo "python3.13 not found"
          command -v python3.14 || echo "python3.14 not found"
          echo "Python version:"
          python --version

      - name: Try calling python3.13
        shell: bash
        run: |
          python3.13 --version || echo "python3.13 not callable"
      - name: Try calling python3.14
        shell: bash
        run: |
          python3.14 --version || echo "python3.14 not callable"
