# .github/workflows/test-python-versions.yml
name: Test Python Minor Versions freethread

on:
  # push:
  #   branches:
  #     - test-973
  workflow_dispatch:

jobs:
  test-multiple-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-11-arm, macos-15-intel, ubuntu-22.04-arm]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13t and 3.14t
        # uses: actions/setup-python@v6 #test
        uses: priya-kinthali/setup-python@test-1079-new
        with:
          python-version: |
            3.13t
            3.14t

      - name: Check available python executables
        shell: bash
        run: |
          echo "Checking python executables"
          which python
          which python3
          which python3.13t || echo "python3.13t not found"
          which python3.14t || echo "python3.14t not found"
          command -v python || echo "python not found"
          python3.13t -VV || echo "python 3.13t not found"
          python3.14t -VV || echo "python 3.14t not found"
          echo "Python version:"
          python --version

      - name: Try calling python3.13t
        shell: bash
        run: |
          python3.13t -VV || echo "python3.13t not callable"

      - name: Try calling python3.14t
        shell: bash
        run: |
          python3.14t -VV || echo "python3.14t not callable"
