name: Test 1309

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  latest-latest-in-practice-26-on-host-and-in-container:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Show host / container info
        run: |
          echo "=== /etc/os-release ==="
          cat /etc/os-release || true
          echo "=== uname -a ==="
          uname -a
          echo "=== whoami ==="
          whoami
          echo "=== RUNNER_OS / RUNNER_ARCH ==="
          echo "RUNNER_OS=$RUNNER_OS"
          echo "RUNNER_ARCH=$RUNNER_ARCH"


      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Verify Python
        run: |
          which python
          python --version
          python -c "import sys, platform; print(sys.executable); print(platform.platform())"

  test-26-on-host-and-24-in-container:
    runs-on: [self-hosted]
    container: ubuntu:24.04
    steps:
      - name: Show host / container info
        run: |
          echo "=== /etc/os-release ==="
          cat /etc/os-release || true
          echo "=== uname -a ==="
          uname -a
          echo "=== whoami ==="
          whoami
          echo "=== RUNNER_OS / RUNNER_ARCH ==="
          echo "RUNNER_OS=$RUNNER_OS"
          echo "RUNNER_ARCH=$RUNNER_ARCH"

      - uses: actions/checkout@v6

      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            apt-get update && apt-get install -y sudo
          fi
      - name: Fix pip cache permissions
        run: sudo chown -R $(whoami) /github/home
      - name: Clear cache
        run: |
              mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
              mkdir -p "${{ runner.tool_cache }}"
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Verify Python
        run: |
          which python
          python --version
          python -c "import sys, platform; print(sys.executable); print(platform.platform())"
