name: Test Python 3.8 Install without Rosetta

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python38:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print macOS and Architecture Info
        run: |
          echo "Runner Architecture: $(uname -m)"
          echo "CPU Info: $(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo 'Not available on Apple Silicon (arm64)')"
          echo "macOS Version:"
          sw_vers
      - name: Check if Rosetta is installed
        run: |
          if pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto >/dev/null 2>&1; then
            echo "Rosetta is installed"
            pkgutil --pkg-info com.apple.pkg.RosettaUpdateAuto
          else
            echo "Rosetta is NOT installed"
          fi

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          # architecture: 'arm64'

      - name: Check Python version
        run: python3 --version

      - name: Check if Python binary is Universal2
        run: |
          lipo -archs $(which python3)
      # - name: Check architecture of extracted files
      #   run: |
      #     file /Users/runner/hostedtoolcache/Python/3.8.10/arm64/bin/python3
