name: pip-testing

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest, macos-latest, macos-13]
        python-version: [ '3.14']
        pip-version: ['23.2.1']
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: priyagupta108/setup-python@pip-version-input
      # uses : actions/setup-python@v5
      with:
        python-version : '${{ matrix.python-version }}'
        pip-version: ${{ matrix.pip-version }}
        allow-prereleases: true
        
    - name: Check pip version
      run: pip --version
    - run: pip install requests
