name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        # os: [windows-latest, macos-latest, ubuntu-latest]
        os: [windows-latest]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11.9
      # - name: Check for Python 3.8.908 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.8.908 /s /b
      - name: Check for Python 3.11.9 on Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Checking Python DLLs..."
          dir C:\hostedtoolcache\windows\Python\3.11.9 /s /b
      # - name: Check for Python 3.10.17 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.10.17 /s /b
      # - name: Check for Python 3.11.12 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.11.12 /s /b
      # - name: Check for Python 3.12.10 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.12.10 /s /b
      # - name: Check for Python 3.13.3 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.13.3 /s /b