name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.13
            3.9

      - name: Verify Python installation
        run: |
          echo "Checking Python executables on ${{ matrix.os }}"
          python --version
          python3 --version || echo "python3 not found"
          python3.9 --version || echo "python3.9 not found"
          python3.13 --version || echo "python3.13 not found"
          ls -la $(dirname $(which python)) || echo "Directory listing failed"  