name: Test pipenv
on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, windows-latest, windows-2019, windows-11-arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear cache
        run: |
            mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
            mkdir -p "${{ runner.tool_cache }}"
      - name: Set up Python
        # uses: actions/setup-python@v5
        uses: priya-kinthali/setup-python@test-1079
        with:
          python-version-file: '.tool-versions' # Read python version from a file pyproject.toml, .python-version or .tool-versions
          # freethreaded: true
      - name: Verify Python Version
        run: |
          which python3.13



