# .github/workflows/test-python-versions.yml
name: Test Python patch Versions cached 

on:
  # push:
  #   branches:
  #     - test-973
  workflow_dispatch:

jobs:
  test-multiple-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13t 
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.13.3
            3.12.10
            3.11.9
            3.10.11
            3.9.13

      - name: Check available python executables
        shell: bash
        run: |
          echo "Checking python executables"
          which python
          which python3
          which python3.13.2t || echo "python3.13.2t not found"
          which python3.13.3 || echo "python3.13.3 not found"
          which python3.12.10 || echo "python3.12.10 not found"
          which python3.11.9 || echo "python3.11.9 not found"
          which python3.10.11 || echo "python3.10.11 not found"
          which python3.9.13 || echo "python3.9.13 not found"
          command -v python || echo "python not found"
          python3.13.2t -VV || echo "python 3.13.2t not found"
          command -v python3.13.3 || echo "python3.13.3 not found"
          command -v python3.12.10 || echo "python3.12.10 not found"
          command -v python3.11.9 || echo "python3.11.9 not found"
          command -v python3.10.11 || echo "python3.10.11 not found"
          command -v python3.9.13 || echo "python3.9.13 not found"
          echo "Python version:"
          python --version

      - name: Try calling python3.13.2t
        shell: bash
        run: |
          python3.13.2t -VV || echo "python3.13.2t not callable"

      - name: Try calling python3.13.3
        shell: bash
        run: |
          python3.13.3 --version || echo "python3.13.3 not callable"
          python3.13.3 hello.py || echo "Failed to run hello.py with python3.13.3"
      - name: Try calling python3.12.10
        shell: bash
        run: |
          python3.12.10 --version || echo "python3.12.10 not callable"
          python3.12.10 hello.py || echo "Failed to run hello.py with python3.12.10"
      - name: Try calling python3.11.9
        shell: bash
        run: |
          python3.11.9 --version || echo "python3.11.9 not callable"
          python3.11.9 hello.py || echo "Failed to run hello.py with python3.11.9"
      - name: Try calling python3.10.11
        shell: bash
        run: |
          python3.10.11 --version || echo "python3.10.11 not callable"
          python3.10.11 hello.py || echo "Failed to run hello.py with python3.10.11"
      - name: Try calling python3.9.13
        shell: bash
        run: |
          python3.9.13 --version || echo "python3.9.13 not callable"
          python3.9.13 hello.py || echo "Failed to run hello.py with python3.9.13"


