name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.13
            3.9
      - name: Verify Python executables
        run: |
          echo "Checking Python executables on $RUNNER_OS"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            dir C:\hostedtoolcache\windows\Python
            where python3.13 || echo "python3.13.exe not found"
          else
            ls -l /opt/hostedtoolcache/Python
            which python3.13 || echo "python3.13 not found"
          fi
