name: Test Python patch Versions

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-multiple-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11.8
            3.11.7
            3.10.17
            3.9.22
      - name: Check available python executables
        shell: bash
        run: |
          echo "Checking python executables"
          which python
          which python
          which python3.10.17 || echo "python3.10.17 not found"
          which python3.9 || echo "python3.9 not found"
          command -v python3.11 || echo "python3.11 not found"
          echo "Python version:"
          python --version
          python3 --version
      - name: Try calling python
        shell: bash
        run: |
          python --version || echo "python not callable"
          python hello.py || echo "Failed to run hello.py with python"
      - name: Try calling python3
        shell: bash
        run: |
          python3 --version || echo "python not callable"
          python3 hello.py || echo "Failed to run hello.py with python"
      - name: Try calling python3.11
        shell: bash
        run: |
          python3.11 --version || echo "python not callable"
          python3.11 hello.py || echo "Failed to run hello.py with python3.11"
     