name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        os: [windows-latest]
        # architecture: [x86, x64]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clear existing Python versions
        run: |
          rm -rf /Users/runner/hostedtoolcache/Python
      - name: Set up Python
        uses: priya-kinthali/setup-python@test-1079
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13

      - name: Check for Python 3.8.10 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.8.10 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.8.10\*.exe /s /b
      - name: Check available python executables
        shell: bash
        run: |
          echo "Checking python executables"
          which python
          which python3
          which python3.8 || echo "python3.8 not found"
          which python3.9 || echo "python3.9 not found"
          which python3.10 || echo "python3.10 not found"
          which python3.11 || echo "python3.11 not found"
          which python3.12 || echo "python3.12 not found"
          which python3.13 || echo "python3.13 not found"
          command -v python || echo "python not found"
          command -v python3.8 || echo "python3.8 not found"
          command -v python3.9 || echo "python3.9 not found"
          command -v python3.10 || echo "python3.10 not found"
          command -v python3.11 || echo "python3.11 not found"
          command -v python3.12 || echo "python3.12 not found"
          command -v python3.13 || echo "python3.13 not found"
          echo "Python version:"
          python --version

      - name: Try calling python3.8
        shell: bash
        run: |
          python3.8 --version || echo "python3.8 not callable"

      - name: Try calling python3.9
        shell: bash
        run: |
          python3.9 --version || echo "python3.9 not callable"
      - name: Try calling python3.10
        shell: bash
        run: |
          python3.10 --version || echo "python3.9 not callable"

    