name: Test 1079

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        # os: [windows-latest, macos-latest, ubuntu-latest]
        os: [windows-latest]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: |
      #       3.9
      #       3.13
      - name: Download Python 3.13.1
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.13.1/python-3.13.1-amd64.exe" -OutFile "python-3.13.1-amd64.exe"

      - name: Install Python 3.13.1
        run: |
          if (!(Test-Path -Path "python-3.13.1-amd64.exe")) {
              Write-Error "Python installer not found in the current directory."
              exit 1
          }
          Start-Process -FilePath "python-3.13.1-amd64.exe" -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Verb RunAs -Wait -PassThru | Out-Null
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Python installation failed with exit code $LASTEXITCODE."
              exit $LASTEXITCODE
          }
          Write-Output "Python 3.13.1 installed successfully."
      - name: Find Python Installation
        run: |
          Get-ChildItem -Path "C:\Program Files" -Recurse -Include python.exe

      # - name: Verify Python Installation
      #   run: |
      #     python --version
      #     pip --version

      # - name: Check for Python 3.13 on Windows
      #   if: runner.os == 'Windows'
      #   shell: cmd
      #   run: |
      #     echo "Checking Python DLLs..."
      #     dir C:\hostedtoolcache\windows\Python\3.13.1 /s /b
      # - name: Check for Python 3.13 on macOS
      #   if: runner.os == 'macOS'
      #   shell: bash
      #   run: |
      #     echo "Checking Python files on macOS..."
      #     find /Users/runner/hostedtoolcache/Python/3.13.2

      # - name: Check for Python 3.13 on Linux
      #   if: runner.os == 'Linux'
      #   shell: bash
      #   run: |
      #     echo "Checking Python files on Linux..."
      #     find /opt/hostedtoolcache/Python/3.13.2
      # - name: Check for Python 3.13 on non-Windows
      #   if: runner.os != 'Windows'
      #   run: |
      #     command -v python3.13 || echo "python3.13 not found on ${{ matrix.os }}"
      

